### PR TITLE
chore: update did-common-java.version to 1.2.0

### PR DESCRIPTION
**Pull request by fqutishat**
- 1.2.0 include fix https://github.com/decentralized-identity/did-common-java/commit/d299030ba04dbcdadb65649fec8a4772bc662e69

Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>

### CODE REVIEW

**Comment by fqutishat** [comment]
@peacekeeper @cihanss can you please review

**Comment by fqutishat** [comment]
@peacekeeper @cihanss  After merge this PR, How can I update ion driver image in https://uniregistrar.io/

**Review by peacekeeper — APPROVED** [review]

**Comment by fqutishat** [comment]
@peacekeeper Thank you for your approve. @cihanss can we merge this PR ?

**Comment by cihanss** [comment]
We manage [the version of did-common-java ](https://github.com/decentralized-identity/universal-registrar/blob/6f6249dcae99fa9b306ab211d63e919d05530ff3/pom.xml#L78) in its parent project. @peacekeeper, any reason to change this behavior?

**Comment by fqutishat** [comment]
@cihanss I update parent project. https://github.com/decentralized-identity/universal-registrar/pull/64

**Comment by fqutishat** [comment]
@cihanss I can close this PR and open new PR when this PR is merged https://github.com/decentralized-identity/universal-registrar/pull/64

**Pull request closed without merging**
